name: Deploy Extension System

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: set_up_boost_thirdparty
              run: |
                    sudo apt-get install libboost-all-dev

            - name: extension_init_git_submodules
              run: |
                    git submodule update --remote
                    git submodule update --init --recursive

            - name: build_yaml_thirdparty
              run: |
                  cd thirdparty/yaml-cpp
                  mkdir build
                  cd build
                  cmake ..
                  make -j
                  sudo make install

            - name: build_jsoncpp_thirdparty
              run: |
                    cd thirdparty/jsoncpp
                    mkdir build
                    cd build
                    cmake ..
                    make -j
                    sudo make install

            - name: build_extension_system
              run: |
                    cd build
                    cmake ..
                    make -j
                    make

            - name: extension_cleanup
              shell: bash
              run: |
                    find ${{ github.ref_name }} -name ".git" -prune -exec rm -rf {} +

            - name: create_extension_tar_files
              run: |
                    tar -czf ${{ github.ref_name }}.tar.gz ${{ github.ref_name }}
                    tar -cJf ${{ github.ref_name }}.tar.xz ${{ github.ref_name }}

            - uses: softprops/action-gh-release@v1
              with:
                files: |
                    ${{ github.ref_name }}.tar.gz
                    ${{ github.ref_name }}.tar.xz
                
